server:
  port: 9004

spring:
  application:
    name: index12306-pay${unique-name:}-service
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.128:8848
      password: nacos
      username: nacos
    sentinel:
      transport:
        dashboard: localhost:8686
        port: 8719
  data:
    redis:
      host: 192.168.100.128
      port: 6379
      password: 123456

rocketmq:
  name-server: 192.168.100.128:9876
  producer:
    group: index12306_pay-service_common-message-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1

pay:
  alipay:
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqaGXKD3J9Nj1+n4yjY69Gkng0hYXYvr5sdtXqYHDOH1UcLBgaee4DW5016XVMMLZ5MX02bdqN7ndCY6VpgSkDyPe2vS5wf+drDcSArMKJlUXfJqXUb80kJrn7TZscLza++stGqOzDTR0D3Q4tjR7GgKaUCG2WCjVRgXfEt3/OHHExaCivlMUJ5OQW250gFho0ShyXKx11PJGmSgiWmOcVsq+HgPjNn1taCjUcE+LsghmYdH9fbu3Y4Y5x0jawnFP98oJCxy0PZylJQtnvZq0AHMcK0lGNnYY5Ysz/b9CPS1Aua8f40uiX5+rjohk+GQ4HcuIfkEGRNDKR66moDxJ2QIDAQAB
    app-id: 9021000162650968
    charset: UTF-8
    format: json
    notify-url: http://rd4854da.natappfree.cc/api/pay-service/callback/alipay
    private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDEaCidrOCpMYreI7GvuinpiYiozdALy9EQviynPSvAkfuP9Nq3Q09diNabW8pxil4u69Xmvi4MYU4+r9RYcCAeJQvaoir4ioLavoxe4DaheHVZlZH4IquS+bMH4e5G3SJmph4DhLChXbuZvLmA4rDZs4fo/wEvsbHcZuh9Bj+RK/X8qaaOwYHKION0juyZldd2b62r1ivKQpJIgYgBrb0OdpUFpkxcl35GEPdZnhsdFkWhotlcttcp0uSl4BpbKDaniiSl1o9tnka6upfwZy8NqY6WzmrcZPaA6FfKY2HZR1FeWoTD829GdI6+CmiJSiJZnkMP26ErTBoLTHdFCmrvAgMBAAECggEBAJ3aGMqg5u8Uokdm6KgTNxw7LVp+D3drl9uc/MZso31h1o0cfaxMrLy//btfSpV2X7vWT1PkBZ5tljVLm554f1e67owJSf/3UrP78VVPXpjn92jIjUiglMTLatgq/RZ3I+7cE8NAIbWPX/dvdqfficNuRw075fgvGIPLMY9KNky1X2J+N8MeNbCs8eOrQ/I+iv0V5uLx3L0POFK2BDSLejFkuhQkvTQ7CsCzqKPUg8dnPacilvKRN5mWAKaqrjLvgtQVXtoM11Hp/fUJKiFH1MF7XLVDP5yY22zhpNeUncPvEFbjhlwuhVCe4QPZJ6/wnOSCgh6+BodfwT2OLD2i8AECgYEA611H4LbS+fkbqDCguEMWv3OCemOK7bnn2jkD2gL0iYutU00U2wP0nXAuR3kbdDvHn0KpiaHKTwt7FH0N407Gt393msmrdrNsNPtmxx+8QSwkV1bKj6Wgb7ahyWY7qAXfdjcUFhFDoAXo4Tu2w3x1cprm2iLu9VB0gvNXMtF0K+ECgYEA1aB7doR2L7cIy9N/Rov8dpgS+XXmJoGtM2KhB19iz61ALii1wItgUSXVu5U/lQOgH01l4TO63mJl/oXtfJTKX2lG3A9HyPJ9lD2U/HfGCiRRvqJ3AGLRoTO8+5ru2q20lrEh5YXy1cnbYNH8Vk73xgnW8y8tz+lGmIGkgB348M8CgYAnuT2pYpHnGLEfSN3HW6NaOq+Z4nUPPGIyRY8t23PURxvAxHCxqlA9xjI5Y+pLSs+dRI4CqajQgHqMcbLHW4NUcxIHsOPci9nGc2vcTbHjOgUELKTRa73RPPy/Vh7Zc+xMMm2Ub+N+/aBZa0+kXLwh1J0D0gOMqcCQXWupKwq1YQKBgARtNOG50PEgK9B9a2+8ythyQkJlDQXTPhGIg6mxcky3XFMYiNuah75muE0QxKaD0reTVP8boU2mYFKr18XzF1ZuygcZUfV6ANwngoTQvovLQN5gY3LgmVNrzQixpy1k2A8fUIJ/Cg8gBam18DKhpES4Q3n6ikp6nPngBdaZyGTFAoGATLdia/wEhJ1dyTMXlXfx5X0zyzkDPEz9UwJYBswJxSGpUceX2Kfz5tj+uqAcnMzBl40T3on9llmOVsC5ih0r2GtxxNCYEXj3SUWR66CMaVViGr1x2gMZvbb1/yLyfhfqM/c+6O2ruf+1gNkJ6DDHhg/2thVCacLW37c4CI3fNS4=
    server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
    sign-type: RSA2

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mapper-locations: classpath:mapper/*.xml

framework:
  fastjson:
    safe-mode: true
  cache:
    redis:
      value-timeout: 16
      value-time-unit: days

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
