server:
  port: 9004

spring:
  application:
    name: index12306-pay${unique-name:}-service
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.128:8848
      password: nacos
      username: nacos
    sentinel:
      transport:
        dashboard: localhost:8686
        port: 8719
  data:
    redis:
      host: 192.168.100.128
      port: 6379
      password: 123456

rocketmq:
  name-server: 192.168.100.128:9876
  producer:
    group: index12306_pay-service_common-message-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1

pay:
  alipay:
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqaGXKD3J9Nj1+n4yjY69Gkng0hYXYvr5sdtXqYHDOH1UcLBgaee4DW5016XVMMLZ5MX02bdqN7ndCY6VpgSkDyPe2vS5wf+drDcSArMKJlUXfJqXUb80kJrn7TZscLza++stGqOzDTR0D3Q4tjR7GgKaUCG2WCjVRgXfEt3/OHHExaCivlMUJ5OQW250gFho0ShyXKx11PJGmSgiWmOcVsq+HgPjNn1taCjUcE+LsghmYdH9fbu3Y4Y5x0jawnFP98oJCxy0PZylJQtnvZq0AHMcK0lGNnYY5Ysz/b9CPS1Aua8f40uiX5+rjohk+GQ4HcuIfkEGRNDKR66moDxJ2QIDAQAB
    app-id: 2021000122637271
    charset: UTF8
    format: json
    notify-url: http://s977b96e.natappfree.cc/api/pay-service/callback/alipay
    private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCIM+Bel2RuCgR6lzhh5dilRXeVGqTdjCOm+RiVMEPDIiU2jmPO1Ac192V7LSyh1lMFZ4V1YmWPwZujkmlHQdsT6o2bp1FEP/dnAssKFjC9ET34feJT/22F/ESMXjQG5eu8hj+4khVjJpUhyAZWQfSI+GCcDXjOP8B5fTM8qPthRFKs4w++q6bmqykzehrwK/CzawNmBYUJiw9LAE+i8XgGe3Km89K0/E9QeMtInCk5hrNZ61rG4Emde0s4DC8HFMQGp3hlUf28DOoWXIz4tLYgHsoTAoO7d28ZLCNy8u6TzGiKpNFooPhDi8uEh/YA472p0GqcA7C6eL2SFnEC8k3ZAgMBAAECggEBAIIYOule5ZiNjPWjV0F7D1HdZnlO98Z9wtgL+cUWUsMh7DWOEBtQPor3gUEERytV0frJhJo4oBWNsiGtCU38w0rksNnKGT99ccw8yL8brvYIcA7X/sSIp45hBQCmQj+MgXyTJm4farpH8g5QRm1Bllb2FyE3ZPprvmbMhZIdPe8KtJOu7jCFfbmIgD9u7RF4kjoZxlyBoIQE8xrs8JpGKAWYEBUCfvyxQH1e+W7ditu+CXmwz11Vtmt9bdi+enFT4yspxaImx4wy0lXnXKhZMFUw9WGPhWMRbiaS9t/+Xt5P5s5I+VtSy3fggCc+qIVwD+AR+lWRTIxhGp6SXi80ZQECgYEAwYSWfszZpvhaW8CVL9kSVZVCNWZzGacY5HHg9Lk9WPUSiPmaz3WGcnpyyM//jI+TVQj6YnVlCBRgQUAfQ82Tq7WJP8gXfwxf9eSjLiuc4OCzIc2/2ag8hNGGllvO2LBeKzI+gAPruwE7sOF89DgxPE0J5S4C50jQJ6lE4q8PkbECgYEAtC3WoZVSxYs1KGbIw3f73Ah+JPEaYLIhMnalIKGeD5gSR8H/bRspBct3Yta97Ufe2Z5Me4L8UPLKE3Shy+QYkj9qGrHvvQpOukQvjIYffn1bLIaTWzFXrzwAzvYoTWwVyyvjtt8G44XGXdq5N1c/7yrTawmQdjjhT/AcQNcFIKkCgYAOJlu6uc/QXah9vP8rmHu2tks5DFyuK4GucoU4X7MUphbM3TNsp/NEu59Y/5x38qebOCTWvi69AIBpRP8EPivmCkgW2dKd/5GksSsdXSMDbmqqthipGZwTOh7VL7FYNs0r62iWg7Lg4Z4zuMkiMlmnRxrKHysnLjPKMp5O1O4WgQKBgQCB1ZoY+5oWgVZ/03kN6ZLSnkgP5LEGRrXHQFmDJxLX19QsYy3k+DJaW6Ce13Eq36RFGl2wjtW0mw9kb6H7Y1UVZZ7Wt6uyhA/xBxtgXnGpWzls31il2Ot/eXR3rkeiaqVVrz261AGJyCcGEItwxm1qsWiBc/XmStyJFtO1IXwvaQKBgHIyL13zvDLD+e44o+0NKKJxX6apVxnTV3FLKHIYCh1yaoO10i/PpgPzsjIq41eZ8lxAB7xZfxX5BICH//TO6tYkZRdDwqbBCtz//3FplfR2g5DbnBLAFkjJnVCsSaSZyW+U57kIrT4xYV5LLgyshYg6dVwoN06Xi2xS7KTHhkny
    server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
    sign-type: RSA2

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mapper-locations: classpath:mapper/*.xml

framework:
  fastjson:
    safe-mode: true
  cache:
    redis:
      value-timeout: 16
      value-time-unit: days

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
